<?php

/**
 * @file
 * Handles film from the libry film service.
 */

/**
 * Implements hook_menu().
 */
function ding_redia_film_menu()
{
  $items = array();

  $items['admin/config/ding/ding_redia_film'] = array(
    'title' => 'Ding Redia Film',
    'description' => 'Manage ding redia film module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_redia_film_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/ding_redia_film.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['film/redia'] = array(
    'title' => 'Redia Film',
    'page callback' => 'ding_redia_film_render',
    'access arguments' => array('access content'),
  );

  $items['film/redia/%'] = array(
    'title' => 'Redia Film',
    'page callback' => 'ding_redia_film_render_film',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );

  $items['film/redia/authenticate/%'] = array(
    'title' => 'Redia Film Authenticate',
    'page callback' => 'ding_redia_film_authenticate',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Renders reacts komponents.
 */
function ding_redia_film_render()
{
  $login_url = ding_redia_film_login_url();
  $agency = variable_get('ting_agency', '');
  $options = ' loginurl: "' . $login_url . '", agency: "' . $agency . '"';

  $content = '
  <div id="root"></div>
  <script
    crossorigin
    src="https://unpkg.com/react@17/umd/react.production.min.js"
    ></script>
    <script
    crossorigin
      src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"
      ></script>
      <script
    type="module"
      src="https://film.libry.dk/libry-film-widget-app.umd.js"
      ></script>
      <script>
    window.addEventListener("DOMContentLoaded", (event) => {
    window.LibryFilm.init({ 
      containerId: "root",
      baseUrl: "/film/redia", 
      bappsApiKey: "12481632",
      bappsCustomerId: "bob",' .
    $options . ' 
    });
  });
  </script>
        ';
  return $content;
}

function ding_redia_film_render_film()
{
}

/**
 * Generate a login url which can be used as a prop for React apps.
 *
 * @return string
 *   Login url.
 */
function ding_redia_film_login_url()
{
  return ding_provider_invoke(
    'openplatform_token',
    'login_url',
    ['query' => ['destination' => '']]
  );
}

/**
 * Authenticates users with the libry film service.
 * 
 * @param string $customer_id
 *   Id off the library which site the user is visting.
 *
 */
function ding_redia_film_authenticate($customer_id = '')
{
  // Ding Varnish will cache requests even for logged in users. Mark this
  // page as not cacheable to bypass Varnish. Uses should not get each others
  // token due to a cached response.
  drupal_page_is_cacheable(FALSE);
  global $user;
  $status = '';
  $film_service_token = null;

  // Check if the logged in user is a library user.
  if (!user_is_logged_in()) {
    $status = 'not_logged_in';
  } elseif (!ding_user_is_provider_user($user)) {
    $status = 'not_library_user';
  }  else {
    $libry_token = ding_redia_film_handle_authentication($customer_id);
    if (isset($libry_token)) {
      $status = 'logged_in';
      $film_service_token = $libry_token;
    } else {
      $status = 'no_token';
    }
  }

  $output = array('token' => $film_service_token, 'status' => $status);
  drupal_json_output($output);
}

function ding_redia_film_handle_authentication($user_id)
{
  $token = ding_provider_invoke('openplatform_token', 'for_user');
  return ding_redia_film_get_film_service_token($token, $user_id);
}


/**
 * Set additional parameters to ting request.
 *
 * @param string $token
 *   Single sign on token.
 *
 * @param string $customer_id
 *   Id off the library which site the user is visting.
 *
 * @return string $libry_token
 *   Returns token from the libry service.
 */
function ding_redia_film_get_film_service_token($token, $customer_id)
{
  $libry_token = NULL;
  try {
    $client = new \GuzzleHttp\Client();
    $jar = new \GuzzleHttp\Cookie\CookieJar;

    $options = [
      'json' => [
        "jsonrpc" => "2.0",
        "id" => 1,
        "method" => "watch.webLogin",
        "params" => ["12481632", $customer_id, $token]
      ],
      'cookies' => $jar
    ];
    $film_service_server = variable_get('ding_redia_film_server', 'https://bapps-be-staging.redia.dk/v2/');
    $response = $client->post($film_service_server , $options);
    $content = $response->getBody()->getContents();

    $jar->toArray();

    $json = json_decode($content, true);
    //file_put_contents("/var/www/drupalvm/drupal/web/debug/film7.txt", print_r(json_encode($json, JSON_PRETTY_PRINT), TRUE), FILE_APPEND);
    if (isset($json['result']) && isset($json['result']['session'])) {
      $libry_token = $json['result']['session'];
    }
  } catch (Exception $e) {
    watchdog('ding_redia_film', 'Unable to retrieve token from Libry service: %message', array('%message' => $e->getMessage()), WATCHDOG_ERROR);
  }
  return $libry_token;
}


